name: build

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!docs/**'
      - '!README.md'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Calculate version
        run: curl -Ls https://solugo.github.io/gitversion/run.sh | GITVERSION=v1.0.5 bash
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: DOCKER_BUILDKIT=1 docker build --tag ghcr.io/${{ github.repository }}:${{ env.VERSION }} --tag ghcr.io/${{ github.repository }}:latest .
      - name: Publish Docker Image
        run: docker push ghcr.io/${{ github.repository }}   
      - name: Deploy to Kubernetes
        uses: deliverybot/helm@v1
        with:
          release: scrumpoker
          namespace: default
          chart: ./chart
          chart-version: '${{ env.VERSION }}'
          token: '${{ github.token }}'
          values: |
            image:            
              repository: 'ghcr.io/${{ github.repository }}'
              tag: '${{ env.VERSION }}'
            ingress:
              enabled: true
              domain: 'poker.solugo.de'
              annotations:
                kubernetes.io/ingress.class: public
                cert-manager.io/cluster-issuer: letsencrypt
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'