name: release

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!docs/**'
      - '!README.md'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Calculate version
        run: curl -Ls https://solugo.github.io/gitversion/run.sh | GITVERSION=v1.0.5 bash
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}